apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  helmVersion: v3
  releaseName: podinfo
  chart:
    git: https://github.com/stefanprodan/podinfo
    ref: v3.x
    path: charts/podinfo
