---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIURzJryBmjBFbKlfweCmemUzm2ymcwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMjAwMjExMTAwNTAwWhcNMjUwMjA5MTAwNTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANx0l2tzlazE7MB/Q5P7QEusLCEhiOLq0AiETrgDOspjBenW7gAbDlZXKE6K9Wh2
    Ozt4T3RcGxo7AybdOWV3x7fxne79+Tg0LgKBs001RaZnyliI2k1iqxG9atfRs6e7
    7g53MnaitCI2MJZVQO9i549eBojrNwg3SGapMkhmJo7aUSntJDhccA+pIm665VHC
    qi8SaN2D5Yu3fVJXTq86vKznNnSFgwYl63h6B/E7zDIutOJ+9ctCHrns3yyw83kA
    /3O64sG8JbflOiVnkK2RwR52FreDM6vodKOb7jwE80no80Iy2EQfePxBZTZXOSc3
    iOhENtaExkMOChBSbTs15YMuQBHm8W8INeVZcCfpRgJYkfqIQCoV3ULsMGOqEFYA
    I3p893Zx3Nrm3aDk0rw4J3MaLZDuPlGax+XYic2IiIjrmbCGRKLOJRLZxW2VIUtL
    r/MoeYCLx7diQJSnBZiz1i84P0RE1y5m0henHCthNb8XHP15SSV03FjFkv2o1nVU
    v1kvvcgAlde5ZLWW0hGX6S0ghFYTCiOtJeYRaDvlpzKmGf4EnADDRSg/4LSHz8Z5
    Ix4qltWs9u9sYtUwNs1a7eb77UCcazp3bvD8ejHN14Z105oc0QvXbOpSCL/3s04c
    O/cbv4GTTc7jfudMQw+AO6bwXWI0RhljMFeCGIHYxXJtAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRHoeYVVteTmrx2
    ZGr5LqRkBLeWAjANBgkqhkiG9w0BAQ0FAAOCAgEAERinFwUHPlaikn3X3s695YAZ
    /jkYrpONKndF/tB/ez58AN+0zELs5K6xjUVuoML5Im26TU1wXJqTEr4fnn9lZMBz
    RcOTPYHEgCZBTmVqbP9YYbBwBdqi8FuKeO6goDeVXYKSnjdVdUjks2WoG29BlQ9D
    ZWE0iLcv/uaETHwcdorIQgh+luEjLyepQD8a8TSrLFz6r2GKIdg7I2uMXbeTFeCE
    7u5nCnE8QQY6qStlwwPqK6oDBpYHW+Ml6ckBywszlbIihpWCEvz6TVHYUBNvjf9X
    7JcfnAxFi13qYY2unp1K+PGnIDZidXCQ3yUykDGu5VaqlUAZQtXDp6DQ7sepfqah
    AbRq1KFJ83eodXaoDOw8DwuwzAAdWVOWGWlG/1r25WEAZrX8i94Bta552miNXw8N
    vBtzdUtDjUF+RnifNPhmkIwp6Lz82lz7xFBji5T57lReyTBnXQ2ADoOi1oVNz2DV
    58rjvDY64m8oBUei7OjgbXI3P9Zsg8X6sHjrZgaD+yNGIJBrOMu0QhnbNm94gLQ8
    8IvHDlEAHHRFs/OTH7s6zbCBzkH+o+FIc5ylTthqBcSMsdrju6MUIpEQsR+579uW
    xP+0SqAAvBu6KegRgjFezFY2A0Mqjm/980CsT04VSAhJeZrZ7BjkkiDZADbMYBCf
    2BchMkg3M3o0slgXSsc=
    -----END CERTIFICATE-----
    
