---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUHJ6YZQKQ5fXL4igY4VVmxX/rym4wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMjAwMjEwMTUwMDAwWhcNMjUwMjA4MTUwMDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOQ9SiNi8ITfOO4aLeII1h1blbu40ucQkaNI3xUORQ5Ere80wucIl4BIAh+7UOWR
    AV0wG32SDezos7WyT9ZHdXN+VSCdOZuqFJvDend/DLVecEGMdneal6JXyUgmdNc2
    tLcetnON8SzNLhvc1vZuaF4wTK879c9GAC8dM0/BF1seKg6802hQeTyhNHLcmvj8
    BhxoRdxZ1FKibZ6SmE9YAwPk8q0Woo2h2QfNBvwXo+LOfkPq0aIHGWzIUwN3mQQv
    kLoRYXyd5u/vRpEQ5YmjP4MXg7M8GQJstflxeBBKBunHUyYgRKvAltlYYcMven9h
    p3oR8WqBc9uHcOTn/pc7krpc//hx4VmR8/ns0hfsvdyXqndsY5egnWX6pLiBZRgd
    KA5SLQoryEW8m0ASp1XG+C5rARYw9V+IO8nGkEb6zD55OcOc7Qs0ERoy7tlWFJ4p
    O43IeuTthyrCJGJAxCAxG5wgSPqzIjyBtZZb/bMN2JSlFQK7FC2DnWZ4N2IHcIlO
    UwINOyJjp6k2hzetBHIlElqztrM8YLgxwt0N14b2i0nQ11VQrkup5rJmlijUpmMI
    hsoxz7Kb33Ys8tV4Ocle99mWqEiNE98kz4I22Zf6HMl5efM5+RoCZ619KVDr4dvu
    Ia0wuZdQjgdni5USXGgNTXmDgJtzpGJBWI5cT8bWGrKzAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR/W+vaIVrDtqWx
    ACFBo5WVn5kA8DANBgkqhkiG9w0BAQ0FAAOCAgEAr9wYHl7v27iJqZYMhZUUhOIf
    T+HGOqUVgz+Gb1UzRHsa6eA31qcTpIiEQiDXkH6rPMElkPx5D9J0RdBmOzP9nqi1
    vf0rjKG4xCJ67qaw7vcd+jUxozS15rHOEF77DZIcxVsi6wde37LNu8bWxcCtv4RT
    UHmvq7gY6azDXQAFMOPB134OWTphpJgceES8OpywgGsS0k7ecKrSZMh05msJSaPn
    9yXvku7w0CvNH+v8QBoq7pDWC/7eGkmCihGIzeNo9X3BanQsMgsOW0APM+vNO4KP
    R7W1kCvfG5sLEfMRCf0I80oQnzNStodfq/0SfwHVCdpF5iDUuqpo1/nffm6eHkfp
    Pht2SiApGyG1YsGJOw9L+aNZwosYBzBHIbgm82U+l0v1l08TDoWUHGh0WasfTaOW
    +JrCNFOZhV7BOkYqFrGay6Vgyd819uhaMyeoCKz6/C303w9HmWAiAtU7J3Z3/Tsq
    aS7DF7chRdQ6YMX4kLRNOK4cGpYaJRsHg1qe8n/z0IlKVW9u0qwhPHRlIohKrPtl
    R0DiQu3C5GZA/pzi87PXweax77GM+ei8fCcTa6DhjQDbqN0+T1WRC9yZ97QZcVDq
    DUVAwF3Ad/DQ3QlILeeNrzUz91HBtzHlIPUXac65Qv4nXiOmM6stLbP21zKfh3Qs
    kHsjVA8mrJwDaAv3qw4=
    -----END CERTIFICATE-----
    
